### ISSUE TITLE
issue for document page - Robonomics Smart Home (new Start From Scratch)

### ISSUE THREAD

**Issue by tubleronchik** [airalab/robonomics-wiki#246]
### Issue description

Please, add: version of libraries, warning about possible changing ip address of Raspberry Py.
Change: commands' output from terminal's screenshot to code output. 

### Doc Page

Versions: RASPBERRY PI SETUP
Warning: MQTT SETUP 
Output: MQTT SETUP, ZIGBEE2MQTT SETUP

@nakata5321

**Comment by nakata5321** [comment]
Fixed. Waiting to upload to the master branch.
