### ISSUE TITLE
[Issue]: Add Robonomics Smart Home Demo page

### ISSUE THREAD

**Issue by PaTara43** [airalab/robonomics-wiki#248]
### Issue description

This may be a small tutorial page for the user to complete. I think it's the smart bulb https://dapp.robonomics.network/#/lights-up. 

### Doc Page

https://github.com/airalab/robonomics-wiki/blob/test-code/data/sidebar_docs.yaml#L6

**Comment by nakata5321** [comment]
Demo will be on academy.
