### ISSUE TITLE
issue for document page - Manual start of the Robonomics network, consisting of 3 nodes(ru)

### ISSUE THREAD

**Issue by Splinter1984** [airalab/robonomics-wiki#277]
### Issue description

The download link for `SubKey` is not valid.
If you find early releases, there `Subkey` is a fairly old version.
Maybe update link to ![SubKey](https://docs.substrate.io/reference/command-line-tools/subkey/)?

### Doc Page
Maintain > Deploy Robonomics Test Network > Manual start of the Robonomics network, consisting of 3 nodes

**Comment by dergudzon** [comment]
This manual is deprecated and will not work for actual version of Robonomics (2.3.0), even if we change **subkey** to **robonomics key**. So need to remove it from wiki.
