### ISSUE TITLE
[Checking up-to-date]: How to build collator node from source

### ISSUE THREAD

**Issue by Fingerling42** [airalab/robonomics-wiki#310]
### Issue description

Author: @dergudzon

Since we are updating the wiki and you are the author of the article, you need to check if this article is up to date. 

You options:
- If the article is up to date, then make a comment about it in the issue.
- If the article needs to be update, and you will definitely do it, then write about it in the issue. Let us know when you will finish it.
- If you are unlikely to update the article, write about it and we will delete it.

In any case, the article will be removed from the sidebar, and will be available only through a direct link. If there are no updates after 3 months, the article will be automatically removed from the wiki.

Please, add the **tools parameter** to the article, if applicable, to indicate which versions of the software are needed for this article.

Also, consider adding dependencies to the article for automatic deprecation reminders. This is explained here: 
https://github.com/airalab/robonomics-wiki-deprecation-notifier

### Doc Page

https://wiki.robonomics.network/docs/en/how-to-build-collator-node/

**Comment by dergudzon** [comment]
Updated this article.
