### ISSUE TITLE
Replace R'n'D with a link to a doc in IPFS

### ISSUE THREAD

**Issue by PaTara43** [airalab/robonomics-wiki#328]
https://wiki.robonomics.network/docs/en/r-and-d-based-on-robonomics-network/

RnD cases description - https://ipfs.io/ipfs/QmUbQTQknKLuDB8SmJF9pUhkTPdJbXp5ghDwp7oXwwDb9V

Probably place the link on start page/robonomics.network

As for now, page is hidden from sidebar

**Comment by nakata5321** [comment]
Also we have this book in English: https://ipfs.io/ipfs/QmRHvtsEViqHFN6Mt66p9o5MvvzB2H5uvfMTi8maAnLmfi

**Comment by Fingerling42** [comment]
Deleted
