### ISSUE TITLE
issue for document page - Robonomics Smart Home Overview

### ISSUE THREAD

**Issue by MichaelGitty** [airalab/robonomics-wiki#388]
### Issue description

Ошибки в тексте Overview: 
For your smart home the modern IoT market provides a wide range of solutions. But you are usually tied to centralized cloud providers or expensive proprietary gateways. As a result, you as a user are always dependent on the hardware and infrastructure vendor to run the your smart system. At the same time, your smart home cannot be truly smart without cloud statistics and analytics.

Вот правильный текст: 
For your smart home, the modern IoT market provides a wide range of solutions. But you are usually tied to centralized cloud providers or expensive proprietary gateways. As a result, you as a user are always dependent on the hardware and infrastructure vendor to run your smart system. At the same time, your smart home cannot be truly smart without cloud statistics and analytics.

### Doc Page

https://wiki.robonomics.network/docs/robonomics-smart-home-overview#introduction

**Comment by Fingerling42** [comment]
Thanks! Added fix to PR
