### ISSUE TITLE
The hamburger ui is bad visibility with using light-mode.

### ISSUE THREAD

**Issue by KiichiSugihara** [airalab/robonomics-wiki#60]
# Target
I didn't notice it when I was browsing on my smart phone.
Perhaps there are many others.

[![Image from Gyazo](https://i.gyazo.com/c884c7c3a78d6427da29b2471d410b93.png)](https://gyazo.com/c884c7c3a78d6427da29b2471d410b93)

## Idea
If it's as white as the moon icon, it will be visible.

## Comparison light-mode with dark-mode
[![Image from Gyazo](https://i.gyazo.com/d2d5f0dcf90a7e21be7e333b2871177a.gif)](https://gyazo.com/d2d5f0dcf90a7e21be7e333b2871177a)

**Comment by positivecrash** [comment]
fixed
