### ISSUE TITLE
Link is sticking out with using smartphone

### ISSUE THREAD

**Issue by KiichiSugihara** [airalab/robonomics-wiki#61]
# Bug
ex.
https://wiki.robonomics.network/docs/en/wschool2021-build-dapp-for-end-users/

[![Image from Gyazo](https://i.gyazo.com/bc97d5841fbbf52b49dbdd690a9e54d1.gif)](https://gyazo.com/bc97d5841fbbf52b49dbdd690a9e54d1)

# Idea
Add 'link' property 'word-break'

**Comment by positivecrash** [comment]
Fixed. Thanks for noticing
